/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import ctr.ctrobat0901;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SATYA
 */
public class frmobat extends javax.swing.JFrame {
    
    ctrobat0901 o = new ctrobat0901();

    /**
     * Creates new form frmobat
     */
    public frmobat() {
        initComponents();
        this.bukaForm();
    }
    
    
    public void bukaForm(){
        txtkdobat0901.setText("");
        txtnmobat0901.setText("");
        txtsatuan0901.setText("");
        txtdosis0901.setText("");
        txtstok0901.setText("");
        txtharga0901.setText("");
    }
    
    public void setKdObat0901(String p){
        o.setKdObat(p);
        txtkdobat0901.setText(p);
        txtnmobat0901.setText(o.getDataPelanggan().get(1));
        txtsatuan0901.setText(o.getDataPelanggan().get(2));
        txtdosis0901.setText(o.getDataPelanggan().get(3));
        txtstok0901.setText(o.getDataPelanggan().get(4));
        txtharga0901.setText(o.getDataPelanggan().get(5));
    }
    
    public void simpan(){
        ArrayList<String> vLst = new ArrayList<String>();
        vLst.add(txtkdobat0901.getText());
        vLst.add(txtnmobat0901.getText());
        vLst.add(txtsatuan0901.getText());
        vLst.add(txtdosis0901.getText());
        vLst.add(txtstok0901.getText());
        vLst.add(txtharga0901.getText());
        o.setDataPelanggan(vLst);
        o.simpan();
    }
    
    public void edit(){
        ArrayList<String> vLst = new ArrayList<String>();
        vLst.add(txtkdobat0901.getText());
        vLst.add(txtnmobat0901.getText());
        vLst.add(txtsatuan0901.getText());
        vLst.add(txtdosis0901.getText());
        vLst.add(txtstok0901.getText());
        vLst.add(txtharga0901.getText());
        o.setDataPelanggan(vLst);
        o.edit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan0901 = new javax.swing.JButton();
        btnUbah0901 = new javax.swing.JButton();
        btnHapus0901 = new javax.swing.JButton();
        btnBatal0901 = new javax.swing.JButton();
        txtkdobat0901 = new javax.swing.JTextField();
        txtsatuan0901 = new javax.swing.JTextField();
        txtnmobat0901 = new javax.swing.JTextField();
        txtdosis0901 = new javax.swing.JTextField();
        txtstok0901 = new javax.swing.JTextField();
        txtharga0901 = new javax.swing.JTextField();
        txtCari0901 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM OBAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        btnSimpan0901.setText("SIMPAN");
        btnSimpan0901.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpan0901MouseClicked(evt);
            }
        });
        btnSimpan0901.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan0901ActionPerformed(evt);
            }
        });

        btnUbah0901.setText("UBAH");
        btnUbah0901.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbah0901MouseClicked(evt);
            }
        });
        btnUbah0901.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah0901ActionPerformed(evt);
            }
        });

        btnHapus0901.setText("HAPUS");
        btnHapus0901.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapus0901MouseClicked(evt);
            }
        });

        btnBatal0901.setText("BATAL");
        btnBatal0901.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatal0901MouseClicked(evt);
            }
        });

        txtkdobat0901.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkdobat0901FocusLost(evt);
            }
        });

        txtCari0901.setText("CARI");
        txtCari0901.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCari0901MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSimpan0901)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah0901)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus0901)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(btnBatal0901))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnmobat0901, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdosis0901, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsatuan0901, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtstok0901, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtharga0901, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtkdobat0901, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCari0901)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkdobat0901, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari0901))
                .addGap(7, 7, 7)
                .addComponent(txtnmobat0901, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtsatuan0901, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txtdosis0901, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtstok0901, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtharga0901, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan0901)
                    .addComponent(btnUbah0901)
                    .addComponent(btnHapus0901)
                    .addComponent(btnBatal0901))
                .addGap(28, 28, 28))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KODE OBAT:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA OBAT:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SATUAN:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOSIS:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STOK:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HARGA:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkdobat0901FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkdobat0901FocusLost
        this.setKdObat0901(txtkdobat0901.getText());

        if(txtnmobat0901.getText().isEmpty() == false){
            JOptionPane.showMessageDialog(null, "Data dengan id : " + txtkdobat0901.getText() + " Ditemukan");
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtkdobat0901FocusLost

    private void btnSimpan0901MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpan0901MouseClicked
        this.simpan();
        JOptionPane.showMessageDialog(null, "Simpan data dengan nama : " + txtnmobat0901.getText() + " Berhasil !");
        bukaForm();
        txtkdobat0901.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan0901MouseClicked

    private void btnUbah0901ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah0901ActionPerformed
        this.edit();
        JOptionPane.showMessageDialog(null, "Ubah data dengan id : " + txtkdobat0901.getText() + " Berhasil !");// TODO add your handling code here:
    }//GEN-LAST:event_btnUbah0901ActionPerformed

    private void btnUbah0901MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbah0901MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbah0901MouseClicked

    private void btnHapus0901MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus0901MouseClicked
        o.hapus();
        JOptionPane.showMessageDialog(null, "Hapus data dengan id : " + txtkdobat0901.getText() + " Berhasil !");
        bukaForm();// TODO add your handling code here:
    }//GEN-LAST:event_btnHapus0901MouseClicked

    private void btnBatal0901MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal0901MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatal0901MouseClicked

    private void btnSimpan0901ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan0901ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan0901ActionPerformed

    private void txtCari0901MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCari0901MouseClicked
        this.setKdObat0901(txtkdobat0901.getText());
        
        if(txtnmobat0901.getText().isEmpty() == false){
            JOptionPane.showMessageDialog(null, "Data dengan id : " + txtkdobat0901.getText() + " Ditemukan");
        }
    //GEN// TODO add your handling code here:
    }//GEN-LAST:event_txtCari0901MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmobat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmobat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmobat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmobat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmobat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal0901;
    private javax.swing.JButton btnHapus0901;
    private javax.swing.JButton btnSimpan0901;
    private javax.swing.JButton btnUbah0901;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton txtCari0901;
    private javax.swing.JTextField txtdosis0901;
    private javax.swing.JTextField txtharga0901;
    private javax.swing.JTextField txtkdobat0901;
    private javax.swing.JTextField txtnmobat0901;
    private javax.swing.JTextField txtsatuan0901;
    private javax.swing.JTextField txtstok0901;
    // End of variables declaration//GEN-END:variables
}
